default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sdevtalks_org_development
  #username: sdevtalks_org
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: sdevtalks_org_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
